export const AUTHORIZATION_CAPABILITIES = Object.freeze({
  recordsRead: "records.read",
  leadsCreate: "leads.create",
  leadsUpdate: "leads.update",
  clientsCreate: "clients.create",
  clientsUpdate: "clients.update",
  contactsCreate: "contacts.create",
  contactsUpdate: "contacts.update",
  financialRead: "financials.read",
  projectsCreate: "projects.create",
  projectsAssign: "projects.assign",
  projectsStatusUpdate: "projects.status.update",
  tasksUpdate: "tasks.update",
  meetingsUpdate: "meetings.update",
  notesUpdate: "notes.update",
  gmailFile: "gmail.file",
  calendarCreate: "calendar.create",
  filesRead: "files.read",
  filesUpload: "files.upload",
  filesShare: "files.share",
  dataExport: "data.export",
  auditRead: "audit.read",
  fieldAssignmentRead: "field.assignment.read",
  accessAdminRead: "access_admin.read",
  invitationsCreate: "invitations.create",
  invitationsRevoke: "invitations.revoke",
  usersDisable: "users.disable",
  rolesAssign: "roles.assign",
  sessionsRevoke: "sessions.revoke",
  fieldLinksCreate: "field_links.create",
  fieldLinksRevoke: "field_links.revoke",
  rolePermissionsUpdate: "role_permissions.update",

  // Cataloged but deliberately unmapped until the owner approves them.
  gmailRead: "gmail.read",
  calendarRead: "calendar.read",
  recordsWrite: "records.write",
  jobsRetry: "jobs.retry",
  recoveryManage: "recovery.manage",
  usersManage: "users.manage",
  connectorsManage: "connectors.manage",
} as const);

export type AuthorizationCapability =
  (typeof AUTHORIZATION_CAPABILITIES)[keyof typeof AUTHORIZATION_CAPABILITIES];
